export const LOADING_HEIGHT = 150;
export const NORMAL_HEIGHT = LOADING_HEIGHT + 10;
export const BASE_WIDTH = 290;

export const MISSING_FONTS_TEXT_HEIGHT = 205;
export const MISSING_SINGLE_FONT_HEIGHT = 70;

export const NEEDS_RELOAD_TEXT_HEIGHT = 96;
